@extends('layouts.main')
@section('content')
    <section class="main_slider">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="banner_text text-center lips_div ">
                        <div class="about_con text_main"><h3><strong>User Agreement</strong> ivacay</h3>
                            <p>Welcome to <b>Ivacay,</b></p>
                            <p>This <b>User Agreement</b> (hereinafter referred to as the “<b>Terms</b>” or “<b>Terms &
                                    Conditions</b>” or “<b>Terms of
                                    Service</b>”) shall govern the relationship between <u><b>Ivacay</b>, having its
                                    office at<b>Po Box 81027, Rancho Santa
                                        Margarita, California - 92688</b> </u>(hereinafter referred to the
                                <b>“Company”</b> or <b>“Ivacay”</b> or <b>“us”</b> or <b>“our”</b> or <b>“we”</b>)
                                and you (hereinafter referred to <b>“you”</b> or <b>“your”</b> or <b>“user(s)”</b>) and
                                shall govern your use of our website –
                                <a href="{{route('UI_index')}}">www.ivacay.co/</a> (hereinafter individually as well as
                                collectively, referred to as the <b>“Site”</b> or <b>“Platform”</b>).
                            </p>
                            <p>Ivacay is a one stop all-inclusive company that offers discounted vacation packages and
                                various customized
                                services for our client’s adventures and entertainment. We offer local entertainment,
                                excursions and tour guides.
                                We are an online marketplace platform that connects you with various tour and activity
                                providers and guides.
                                The activities and tours (collectively <b>"Activity"</b> or <b>"Activities"</b>) are
                                offered by a variety of third-party local
                                suppliers (<b>"Suppliers"</b>) and tour guides services are provided by the guides
                                registered on our platform (<b>“Tour
                                    Guides”</b>). Together, the Suppliers and Tour Guides are referred to as the <b>“Service
                                    Providers”</b> in this
                                Agreement. We act as an intermediary between you and the Service Providers. The Service
                                Providers may
                                provide their own terms and conditions in their respective offers/services. (hereinafter
                                referred to as the
                                <b>“Services”</b>)</p>
                            <p>This electronic record is generated by a computer system and does not require any
                                physical or digital signatures.</p>
                            <p>These terms are applicable on the users and other general visitors of the platform.
                                Please read this User
                                Agreement carefully, as this, along with our <b>Disclaimer, Cancellation and Refund
                                    Policy, Community
                                    Guidelines, Cookie Policy</b> and <b>Privacy Policy</b> statement forms the entire
                                agreement between you and Ivacay. If
                                you do not accept this User Agreement in its entirety, then you shall not use the
                                Platform or avail any of our
                                services. In case you are a Service Provider, please refer to our <b>Service Provider
                                    Terms.</b>
                            </p>
                            <p>Additionally, how we collect, use, store, share and transmit your data is governed by our
                                <b> Privacy Policy</b>
                                statement. This User Agreement shall be read in conjunction with our <b> Disclaimer,
                                    Cancellation & Refund
                                    Policy, Community Guidelines, Cookie Policy, </b> and <b>Privacy Policy</b>
                                statement.
                            </p>
                            <h2><span>1.</span>ACCEPTANCE OF THESE TERMS</h2>
                            <p class="left_text">By accessing or using or registering or availing services on/through
                                our Site in any way or by clicking
                                on a button or taking similar action to signify your affirmative acceptance of this User
                                Agreement, you
                                hereby represent that:
                            </p>
                            <p class="left_text2"><span class="left2">(i)</span> You have read, understood, and agreed
                                to be bound by this User Agreement and any future
                                updates and additions to this User Agreement, as published from time to time on the
                                Site.</p>
                            <p class="left_text2"><span class="left2">(ii)</span> You are of <b>sound mind</b> and at
                                least of such minimum <b>legal age</b> as per the jurisdiction in
                                which you reside, in order to form a binding contract with us.<u> In case you are not of
                                    the age of
                                    majority as per the laws of the State that you reside in, then you must have the
                                    permission of
                                    your lawful guardian to use and access the services and content on the Platform, and
                                    to make
                                    purchases.</u>
                            </p>
                            <p class="left_text2"><span class="left2">(iii)</span> We must not have previously disabled
                                your account for violation of law or any of our policies.</p>
                            <p class="left_text2"><span class="left2">(iv)</span> You must have read all the appropriate
                                travel and State guidelines before booking any tour or
                                activity.
                            </p>
                            <p class="left_text2"><span class="left2">(v)</span> You agree, understand and acknowledge
                                that we are an intermediary between you and
                                Suppliers/Tour Guides. The listings posted on our Platform are posted by third party
                                Service
                                Providers, and as such we are only a facilitator between you and such Service Provider,
                                and
                                we cannot be a party to or control in any manner any transactions on or off the Site, or
                                your
                                interaction with the Supplier or Tour Guide, as the case may be. <u><b>Accordingly, the
                                        contract of
                                        service shall be a strictly bipartite contract between you and Supplier/Tour
                                        Guides.</b></u>
                            </p>
                            <p class="left_text2"><span class="left2">(vi)</span> You have read, understood and
                                consented to our <b>Disclaimer, Cancellation & Refund Policy,
                                    Community Guidelines, Cookie Policy,</b> as well as our <b>Privacy Policy</b>
                                statement.</b></u>
                            </p>
                            <h2><span>2.</span>ACCOUNTS, PASSWORDS AND SECURITY</h2>
                            <p class="left_text"><span class="left2">a)</span><b>Account:</b> To access various parts of
                                the Platform, and to avail various services, including without
                                limitation, booking various tours and activities listed by the Suppliers, availing the
                                tour guide
                                services listed by the Tour Guides, making payments, you might be required to register
                                and create
                                an account with us. When setting up and maintaining your account, you must provide and
                                continue
                                to provide accurate and complete information about yourself. As part of the registration
                                process,
                                you will create a password and an account.</p>
                            <p class="left_text"><span class="left2">b)</span><b>Social Media Signup:</b> Besides having
                                the option to sign up using email, you also have an option
                                of signing up using social media accounts, such as Google and Facebook on the Site. In
                                case you
                                choose to sign up using any of the social media accounts, you will be redirected to the
                                website of
                                such social media accounts, and therefore, in addition to this Agreement and our Privacy
                                Policy,
                                you will also be subject to the terms and privacy policy of such social media
                                websites.<u> We are not
                                    liable for any loss caused to you due to any action of such third-party
                                    websites.</u></p>
                            <p class="left_text"><span class="left2">c)</span><b>Security:</b> You are responsible for
                                maintaining the confidentiality of the password and account, and
                                are fully responsible for all activities that occur under your account. You agree to (a)
                                immediately
                                notify us of any unauthorized use of your password or account or any other breach of
                                security, and
                                (b) ensure that you exit from your account at the end of each session. We ask that you
                                should not
                                share your account or password with any third party. We cannot and will not be liable
                                for any loss,
                                damage or other liability arising from your failure to comply with this Section or from
                                any
                                unauthorized access to or use of your account.</p>
                            <p class="left_text"><span class="left2">d)</span><b>Inaccurate Information:</b> If we have
                                reasonable grounds to suspect that any of the information
                                submitted by you is untrue, inaccurate, outdated, or incomplete, or that you have
                                created a
                                duplicate account, in that case, we may terminate your account, and refuse current or
                                future use of
                                any or all of the services.</p>
                            <p class="left_text"><span class="left2">e)</span><b>No Selling:</b> : You are expressly
                                prohibited from selling or transferring or gifting your account to any
                                other person, or from sharing the login credentials of your account with any third
                                party, without
                                our prior written consent.</p>
                            <h2><span>3.</span>HOW CAN YOU USE THE PLATFORM?</h2>
                            <p class="left_text"><span class="left2">i.</span><b>Allowed uses:</b></p>
                            <p class="left_text2"><span class="left2">a) </span><b>Directions of Use: </b>You must
                                follow any and all guidelines or policies or
                                directions of use as associated with each of the services on the Platform.
                            </p>
                            <p class="left_text2"><span class="left2">b) </span><b>Rules: </b>You must read all the
                                details, description, safety instructions and
                                eligibility criteria mentioned in the respective tour and/or activity you are
                                looking to book. If you do not meet the eligibility criterion, or don’t follow the
                                rules or safety instructions, you might not be allowed to participate in the tour or
                                activity. All tours, activities, and services are subject to prevailing guidelines of
                                the appropriate governmental authority. You must follow all the applicable laws
                                and rules, including covid and vaccination related guidelines and directions.
                                Please read all travel and State guidelines as well before booking any service.
                            </p>
                            <p class="left_text2"><span class="left2">c) </span><b>Information: </b>Whenever prompted,
                                you must provide us with the correct,
                                accurate and updated information. All the submitted information will be
                                processed in accordance with our <b>Privacy Policy </b> statement
                            </p>
                            <p class="left_text2"><span class="left2">d) </span><b>Community Guidelines:</b>You must
                                comply with the terms and rules stated in
                                our Community Guidelines.</p>
                            <p class="left_text2"><span class="left2">e) </span><b>Material:</b>For the purposes of this
                                User Agreement, <b>“material” </b> shall mean any
                                logos, trademark, text, video, graphics, sound material, published on the
                                Platform, whether a copyright of Ivacay, Suppliers, Tour Guides, other users, our
                                licensors or any third party. You are not allowed to download or print the
                                material, or extracts from it, in a systematic or regular manner or otherwise so as
                                to create a database in electronic or paper form comprising all or part of the
                                material appearing on the Platform. You must not reproduce any part of the
                                Platform or the material or transmit it to or store it in any other Platform or
                                disseminate any part of the material in any other form, unless we have indicated
                                that you may do so.</p>
                            <p class="left_text"><span class="left2">ii.</span><b>Restricted uses:</b></p>
                            <p class="left_text2"><span class="left2">a)</span>You can’t impersonate others, create
                                duplicate accounts, or provide inaccurate
                                information about yourself, or your experiences.
                            </p>
                            <p class="left_text2"><span class="left2">b)</span>You can’t post, message, raise, or
                                comment on any political, racist or such other
                                issue which affects a person, community or society. You must comply with the
                                <b>Community Guidelines</b> while posting anything on the Site, or messaging the
                                Service Provider.
                            </p>
                            <p class="left_text2"><span class="left2">c)</span>You must not misuse or interfere with the
                                Services or Platform or try to access
                                them using a method other than the interface and the instructions that we
                                provide. You may use our Services only as permitted by law and as per the
                                directions provided by us.
                            </p>
                            <p class="left_text2"><span class="left2">d)</span>You must not:</p>
                            <p class="left_text2">● republish material from this Platform;</p>
                            <p class="left_text2">● sell, rent or sub-license material from the Platform;</p>
                            <p class="left_text2">● show any material from the Platform in public without our
                                consent;</p>
                            <p class="left_text2">● edit or otherwise modify any material on the Platform (other than
                                editing your own information/content as per the method provided);</p>
                            <p class="left_text2">● reproduce, duplicate, copy or otherwise exploit material on our
                                Platform for a commercial purpose; or</p>
                            <p class="left_text2">● redistribute material from the Platform, except for content
                                specifically
                                and expressly made available for redistribution with our written consent and according
                                to our terms;</p>
                            <p class="left_text2">● infringe or violate our Intellectual Property Rights or Intellectual
                                Property Rights of our Service Providers, other users, licensors or any third party;</p>
                            <p class="left_text2">● We reserve the right to restrict your access to any areas of our
                                Platform,
                                or indeed our whole Platform, at our discretion.</p>
                            <p class="left_text2"><span class="left2">e)</span>You must not use our Platform in any way
                                that causes, or may cause, damage to
                                the Platform or impairment of the availability or accessibility of the Platform; or
                                in any way which is unlawful, illegal, fraudulent or harmful, or in connection
                                with any unlawful, illegal, fraudulent or harmful purpose or activity.
                            </p>
                            <p class="left_text2"><span class="left2">f)</span>You must not use our Platform to copy,
                                store, host, transmit, send, use, publish or
                                distribute any material which consists of (or is linked to) any spyware, computer
                                virus, trojan horse, worm, keystroke logger, rootkit or other malicious computer
                                software.</p>
                            <p class="left_text2"><span class="left2">g)</span>You must not conduct any systematic or
                                automated data collection activities
                                (including without limitation scraping, data mining, data extraction and data
                                harvesting) on or in relation to our Platform, without our express written
                                consent.</p>
                            <p>In case of your violation or non-compliance of any of the terms mentioned in this User
                                Agreement, we
                                reserve the right to suspend or terminate your account or your access to the Platform or
                                our services, at
                                our sole discretion.</p>
                            <h2><span>4.</span>WRITING A REVIEW OR LEAVING A FEEDBACK</h2>
                            <p class="left_text">You may be able to rate the services you avail from the Platform, share
                                your experience and provide
                                feedback or review. In such a case, you shall provide your honest and true feedback and
                                opinion. You
                                agree not to post anything or perform any act that is deemed to be abusive, derogatory,
                                political,
                                immoral, unlawful, inappropriate, objectionable, or that infringes on any third-party
                                rights. You must
                                follow our Community Guidelines while posting anything on the Site or messaging the
                                Service
                                Provider. We reserve the right to delete or not display your feedback, at our sole
                                discretion.
                            </p>
                            <h2><span>5.</span>OUR CONTENT AND RIGHTS</h2>
                            <p class="left_text">This Site, its logos, its content, designs, trademarks, trade dress,
                                trade name, all of our features,
                                functionalities and services, shall remain the sole property of the Ivacay, Tour Guides,
                                Suppliers, and/or
                                its licensors, as the case may be. Your use of or access to this Platform or availing of
                                our services shall
                                not in any way transfer or assign to you any ownership or other proprietary rights in or
                                to this Platform,
                                our services, any content (<i>except your own content</i>), designs, published by us or
                                our licensors or third
                                parties. This Site, and the content, including but not limited to the trademark, logo,
                                copyright, design,
                                layout, typography, underlying HTML, Java scripts, text, audio clips, video clips and
                                graphics, and in
                                the expression of the information contained herein, whether as a compilation or
                                otherwise is protected
                                by relevant Intellectual Property laws, rules and regulations. Trademarks, trade names
                                and designs
                                appearing on this Platform are the exclusive property of, or are licensed to the Ivacay
                                and are protected.
                                <u><b>No use of a trademark, trade dress, trade name or design appearing on this
                                        Platform may be
                                        made without the prior written permission of the Ivacay.</b></u></p>
                            <h2><span>6.</span>FEEDBACK RIGHTS</h2>
                            <p class="left_text">To the extent that you provide Ivacay with any comments, suggestions or
                                other feedback regarding the
                                Ivacay platform or Site, as well as other Ivacay services (collective, the
                                “<b>Feedback</b>”), you will be
                                deemed to have granted Ivacay an exclusive, royalty-free, fully paid up, perpetual,
                                irrevocable,
                                worldwide ownership rights in the Feedback. Ivacay is under no obligation to implement
                                any Feedback
                                it may receive from users.
                            </p>
                            <h2><span>7.</span>CONTENT POSTED BY SERVICE PROVIDERS</h2>
                            <p class="left_text">While using our Platform and our services, you may encounter content or
                                information (<i>including
                                    various tours, activities, and guide services</i>) that are posted by Suppliers and
                                Tour Guides. Therefore,
                                there is a likelihood that such information or content be inaccurate, incomplete,
                                delayed, misleading,
                                illegal, offensive or otherwise harmful. Ivacay generally does not review the activities
                                or tours or tour
                                guide services posted by the Service Providers. Please read our detailed
                                <b>Disclaimer</b> posted on the Site.
                            </p>
                            <h2><span>8.</span>RESERVATION OF RIGHT</h2>
                            <p class="left_text"><span class="left2">a) </span> Ivacay is under no obligation to
                                pre-screen any offer or deal posted by third party Service
                                Providers or validate the authenticity or genuineness of the services offered by them.
                                However, Ivacay may at its discretion and/or in accordance with applicable law or on
                                receipt
                                of claim or order, may voluntarily take down any such activity, tour or other service
                                listed on
                                the Platform if Ivacay determines that any offer or deal is in violation of our Service
                                Provider
                                Terms, Ivacay may remove such offer or deal from the Platform without notice. Such
                                actions
                                do not in any manner negate or dilute Ivacay’ position as an intermediary or impose any
                                liability on Ivacay with respect to activity, tour or service posted/listed by the
                                Service
                                Providers on the Platform.
                            </p>
                            <p class="left_text"><span class="left2">b) </span> Ivacay reserves the right to cooperate
                                fully with governmental authorities, private
                                investigators, injured third parties in the investigation of any suspected criminal or
                                civil
                                wrongdoing and/or any third parties alleging a claim against the Service Providers, or
                                the
                                users, as the case may be.</p>
                            <h2><span>9.</span>PRIVACY</h2>
                            <p class="left_text">In order to see what data we collect and how we use or store or share
                                such data, please refer to the
                                detailed Privacy Policy statement available on our Site.
                            </p>

                            <h2><span>10.</span>LINKS TO THIRD-PARTY SITE</h2>
                            <p class="left_text">The Platform might contain links to third-party websites, products and
                                services. Such third-party links
                                are not under the control of Ivacay, and Ivacay is not responsible for any third-party
                                links. Ivacay
                                provides access to these third-party links only as a convenience to you, and does not
                                review, approve,
                                monitor, endorse, warrant, or make any representations with respect to third-party
                                links. You shall use
                                all third-party links at your own risk, and should apply a suitable level of caution and
                                discretion in
                                doing so. Whenever you click on such links, you are taken to such a third-party
                                Platform, and you get
                                out of the jurisdiction of our Platform. <u>Therefore, you shall be governed by the
                                    terms, privacy policy
                                    and other policies of such third-party websites and we suggest that you read those
                                    policies.</u><b> In case of
                                    any damage due to such action of third-party links, Ivacay shall not be
                                    responsible.</b>
                            </p>
                            <h2><span>11.</span>PRICES AND PAYMENT</h2>
                            <p class="left_text"><span class="left2">a) </span>All prices quoted are inclusive prices,
                                i.e. all taxes are already included. However, it is
                                possible that additional local taxes (e.g. local tax) are levied locally. We have no
                                influence on
                                this.
                            </p>
                            <p class="left_text"><span class="left2">b) </span>The booking prices set by the Service
                                Providers may be subject to special provisions,<i> for
                                    example, with regard to cancellations and the refund of payments made.</i> You must
                                independently check before booking whether the respective Service Provider prescribes
                                deviating conditions.
                            </p>
                            <h2><span>12.</span>COVID19</h2>
                            <p class="left_text">The user agrees that due to recent outbreak of COVID-19 which has been
                                declared as pandemic, there
                                may be instances, where the end service provider either cancels the booking or refuses
                                to provide the
                                services, as agreed with the user, by assigning or not assigning any specific reason for
                                such refusal.
                                Refusal of service may be due to the reasons including but not limited to the user:</p>
                            <p class="left_text2">● Exhibiting any symptoms associated with COVID 19; or</p>
                            <p class="left_text2">● Refusing to comply with safety advisories, like wearing protective
                                gear, complying with social
                                distancing norms etc.; or</p>
                            <p class="left_text2">● Suffering of any ailment making the user or other persons vulnerable
                                to the virus; or</p>
                            <p class="left_text2">● Posing a threat to the health and safety of others; or
                            </p>
                            <p class="left_text2">● Any other condition put forward by the appropriate governments.</p>
                            <p class="left_text">In such cases Ivacay will assume no liability for the refusal of
                                service by the end service provider. The
                                user also agrees that refund, if any, for such bookings will be processed by Ivacay to
                                the user subject to
                                receipt of the same from the Service Provider.</p>
                            <p class="left_text">The user further understands that due to the outbreak of COVID-19,
                                there may be frequent changes in
                                guidelines and/ or SOPs issued by the appropriate governments that a traveler will have
                                to follow in
                                order to undertake the travel.</p>
                            <p class="left_text">The user agrees to abide with all such guidelines/SOP while undertaking
                                any travel. In case a user fails
                                to adhere to the same which results in the refusal to travel, Ivacay will not be held
                                liable for such
                                refusal and refund, if any, shall be strictly as per the terms of the Service
                                Provider.</p>
                            <h2><span>13.</span>NON-CIRCUMVENTION</h2>
                            <p class="left_text">You, either alone or through a partner, company or joint-venturer,
                                shall not make any efforts to solicit
                                any of our Service Providers, either directly, or indirectly, in an attempt to receive
                                the services by
                                circumventing us. This Section shall survive the termination or expiration of these
                                terms or our
                                relationship.</p>
                            <h2><span>14.</span>LIMITATION OF LIABILITY</h2>
                            <p class="left_text">To the maximum extent permitted by law, in no event shall Ivacay (or
                                our licensors or affiliates) be
                                liable to you or any third party for any financial loss, travel loss, loss of health,
                                injury, lost data, costs
                                of procurement of substitute products or services, or any indirect, consequential,
                                exemplary, incidental,
                                special or punitive damages arising from or relating to these terms or your use of, or
                                inability to use the
                                Platform, even if Ivacay has been advised of the possibility of such damages. Access to,
                                and use of, the
                                Platform is at your own discretion and risk, and you will be solely responsible for any
                                damage to your
                                person, device or computer system, or loss of data resulting therefrom. We are not
                                liable for any
                                content posted by the Suppliers or Tour Guides, or their action, inaction, behavior or
                                conduct.</p>

                            <h2><span>15.</span>INDEMNITY</h2>
                            <p class="left_text">You acknowledge to defend, indemnify and hold Ivacay, its owners,
                                affiliates, directors, officers,
                                employees, agents, partners, and any other licensors (hereinafter referred to as “<b>Indemnified
                                    Party</b>”)
                                harmless from and against any claim, disputes, fine, liability, demand or expense,
                                including reasonable
                                attorneys’ fees, made by a third party, relating to, or arising from:</p>
                            <p class="left_text"><span>a)</span> Your violation of ours or any third-party right;</p>
                            <p class="left_text"><span>b)</span> Your wrongful or improper use of our services or Site;
                            </p>
                            <p class="left_text"><span>c)</span> Your violation of any applicable laws, rules or
                                regulations;</p>
                            <p class="left_text"><span>d)</span> Your violation of this User Agreement, or any other
                                policy of Ivacay as associated with
                                our services;</p>
                            <p class="left_text"><span>e)</span> The indemnifications set forth above will survive the
                                termination or expiration of this
                                User Agreement and/or your use of our services.
                            </p>
                            <h2><span>16.</span>TRANSACTION AND DISPUTES BETWEEN YOU AND SERVICE PROVIDERS</h2>
                            <p class="left_text"><span class="left2">a)</span> Ivacay is merely a facilitator and is not
                                and cannot be a party to or control in any manner any
                                offers or deals or transactions of sale or purchase, between the Service Providers and
                                you.</p>
                            <p class="left_text"><span class="left2">b)</span> When a service is availed through the
                                deal available on the Platform, the same will be
                                governed by the bipartite contractual arrangement entered into directly between the
                                buyer and
                                the Service Provider. Buyer agrees that Ivacay cannot and does not confirm each Service
                                Provider’s purported identity. Ivacay encourages buyers to exercise discretion and
                                caution
                                while dealing with any Service Provider.</p>
                            <p class="left_text"><span class="left2">c)</span> For any deal, Ivacay does not represent
                                either the Service Provider or the buyer in specific
                                transactions. Ivacay does not control and is not liable to or responsible for the
                                quality, safety,
                                suitability of services, products, lawfulness or availability of the services offered
                                for sale
                                through the deals, or the ability of the Service Provider to complete a sale or the
                                ability of
                                Buyers to complete a purchase. Ivacay does not implicitly or explicitly support or
                                endorse the
                                sale or purchase of any service on the Platform. At no time shall any right, title or
                                interest in
                                the service vest with Ivacay nor shall Ivacay have any obligations or liabilities in
                                respect of
                                any transactions on the Platform.</p>
                            <p class="left_text"><span class="left2">d)</span> User acknowledges that it is fully
                                assuming the risks of conducting any purchase and sale
                                transactions (hereinafter referred to as “<b>Transaction Risk</b>”) in connection with
                                using the
                                Platform, and that it is fully assuming the risks of liability or harm of any kind in
                                connection
                                with subsequent activity of any kind relating to services that are the subject of
                                transactions
                                using the Platform. User acknowledges and undertakes that it is transacting on the
                                Platform at
                                its own risk and is using its best and prudent judgment before entering into any
                                transactions
                                through the Platform.</p>
                            <p class="left_text"><span class="left2">e)</span> Ivacay shall neither be liable nor
                                responsible for any actions or inactions of the user, nor any
                                breach of conditions, representations or warranties of the services and hereby expressly
                                disclaims any and all responsibility and liability in that regard. Ivacay shall not
                                mediate or
                                resolve any dispute or disagreement between buyer and the Service Provider.
                            </p>
                            <p class="left_text"><span class="left2">f)</span> In the event that any user has a dispute
                                with any party to a transaction, such user agrees to
                                release and indemnify Ivacay (and our agents, affiliates, directors, officers and
                                employees)
                                from all claims, demands, actions, proceedings, costs, expenses and damages (including
                                without limitation any actual, special, incidental or consequential damages) arising out
                                of or in
                                connection with such transaction.
                            </p>
                            <p class="left_text"><span class="left2">g)</span> User hereby further agrees, acknowledges
                                and confirms that in case of any dispute, user’s only
                                recourse will be against the Service Provider and we will not be made a party to any
                                such
                                issue and/or dispute between the Service Provider and the user.
                            </p>
                            <h2><span>17.</span>DMCA NOTICE/COPYRIGHT COMPLAINTS</h2>
                            <p class="left_text">Please notify us if you believe any of your intellectual property
                                rights have been infringed on our
                                Platform. Please file your intellectual property infringement claim in accordance with
                                our <b> DMCA
                                    Notice </b> posted on the Site.</p>
                            <h2><span>18.</span>LEGAL ACTION</h2>
                            <p class="left_text">If you are found to be degrading, tarnishing, maligning the image,
                                goodwill or reputation of Ivacay or
                                its directors/owners, by spreading hate, insulting, false, fake reviews or engaging in
                                mala fide actions
                                against the above, strong legal actions will be taken immediately</p>
                            <h2><span>19.</span>GOVERNING LAW AND DISPUTE RESOLUTION</h2>
                            <p class="left_text"><span class="left2"> i.</span><b> Governing Law:</b>This User Agreement
                                and any dispute arising from the same will be
                                governed by applicable laws of the <b>State of California (USA).</b>
                            </p>
                            <p class="left_text"><span class="left2">ii.</span><b>Exclusive Jurisdiction:</b>All
                                disputes must first be attempted to be resolved amicably, failing
                                which, such controversy, conflict or dispute shall be finally settled by bringing it
                                exclusively
                                before the appropriate State or Federal courts situated in <b> Rancho Santa Margarita,
                                    California (USA).</b>
                            </p>
                            <p class="left_text"><span class="left2">iii.</span><b>Disputes between users and Service
                                    Providers: </b>You understand and acknowledge that
                                Ivacay is a mere facilitator between you and the Service Providers, and we in no way are
                                responsible for the conduct of either the users or Service Providers. Therefore, if you
                                have any
                                claim or dispute against one of the Service Providers, you undertake to take it up
                                directly with
                                the concerned Service Provider, as the case may be. Ivacay shall not mediate or resolve
                                such
                                disputes, and nor shall become a party to such disputes. <i>However, if you believe that
                                    any other
                                    Service Provider has violated our Service Provider Terms, applicable law, or any
                                    other policy
                                    of Ivacay, you can file your complaint at <a href="mailto:combinedsun@icloud.com">combinedsun@icloud.com,</a>
                                    and we will take
                                    necessary action in accordance with our policies and applicable law.</i>
                            </p>
                            <h2><span>20.</span>Notices</h2>

                            <p class="left_text">When you use the Platform or send emails to Ivacay, you are
                                communicating with us electronically.
                                You consent to receive electronically any communications related to your use of this
                                Platform. Ivacay
                                will communicate with you by email or by posting notices on this Platform. You agree
                                that all
                                agreements, notices, disclosures and other communications that are provided to you
                                electronically
                                satisfy any legal requirement that such communications be in writing. We may give notice
                                by means of
                                a general notice via electronic mail to your email address as available with us. If You
                                want to give a
                                notice to us, you can do so by dropping an electronic mail to <a
                                        href="mailto:combinedsun@icloud.com">combinedsun@icloud.com.</a>
                            </p>
                            <h2><span>21.</span>Miscellaneous</h2>
                            <p class="left_text"><span class="left2">i.</span> <b>Independent Legal Advice:</b> When you
                                use the Platform or send emails to Ivacay, you are communicating with us electronically.
                                You consent to receive electronically any communications related to your use of this
                                Platform. Ivacay
                                will communicate with you by email or by posting notices on this Platform. You agree
                                that all
                                agreements, notices, disclosures and other communications that are provided to you
                                electronically
                                satisfy any legal requirement that such communications be in writing. We may give notice
                                by means of
                                a general notice via electronic mail to your email address as available with us. If You
                                want to give a
                                notice to us, you can do so by dropping an electronic mail to <a
                                        href="mailto:combinedsun@icloud.com">combinedsun@icloud.com.</a>
                            </p>
                            <p class="left_text"><span class="left2">ii.</span> <b>Headings:</b> The section headings
                                are for convenience only and shall not control or affect the
                                meaning or construction of any provision of this Agreement.</p>
                            <p class="left_text"><span class="left2">iii.</span> <b>Breach:</b> In case of any breach or
                                threatened breach to the provisions of this Agreement, we
                                reserve the right to suspend your account, and your access to our website, at our sole
                                discretion.</p>
                            <p class="left_text"><span class="left2">iv.</span> <b>Severability:</b> If any provision of
                                this User Agreement is held to be unenforceable or invalid,
                                such provision will be changed and interpreted to accomplish the objectives of such
                                provision
                                to the greatest extent possible under applicable law and the remaining provisions of
                                this User
                                Agreement will continue in full force and effect.</p>
                            <p class="left_text"><span class="left2">v.</span> <b>Waiver:</b> Our failure to insist on
                                or enforce strict performance of this User Agreement shall not
                                be construed as a waiver by us of any provision or any right that we have to enforce
                                this User
                                Agreement and nor shall any course of conduct between Ivacay and you or any other party
                                be
                                deemed to modify any provision of this User Agreement.</p>
                            <p class="left_text"><span class="left2">vi.</span> <b>Survival:</b> Notwithstanding any
                                other provisions of this User Agreement, or any general legal
                                principles to the contrary, any provision of this User Agreement that imposes or
                                contemplates
                                continuing obligations on either party shall survive the expiration or termination of
                                this User
                                Agreement, for any reason whatsoever.
                            </p>
                            <p class="left_text"><span class="left2">vii.</span> <b>No Third-Party Beneficiaries:</b>
                                Except as otherwise expressly provided in this User
                                Agreement, there shall be no third-party beneficiaries to this User Agreement.</p>

                            <p class="left_text"><span class="left2">viii.</span> <b>No Assignment:</b> You may not
                                assign this User Agreement (or any rights, benefits or
                                obligations hereunder) by operation of law or otherwise without the prior written
                                consent of
                                Ivacay, which may be withheld at Ivacay’s sole discretion. Any attempted assignment that
                                does not comply with this User Agreement shall be null and void.</p>
                            <p class="left_text"><span class="left2">ix.</span> <b>Entire Agreement: </b> The <b>User
                                    Agreement, Disclaimer, Cancellation & Refund Policy, Community Guidelines, Cookie
                                    Policy </b>and <b>our Privacy Policy </b>statement, together with any
                                additional terms and conditions incorporated herein or referred to herein constitute the
                                entire
                                Agreement between Ivacay and you, relating to the subject matter hereof, and supersedes
                                any
                                prior understanding or agreements (whether oral or written) regarding the subject
                                matter, and
                                may not be amended or modified except in writing or by making such amendments or
                                modifications available on our Site.</p>
                            <p class="left_text"><span class="left2">x.</span> <b>Force Majeure: </b>Ivacay and its third party service providers will be excused from
                                performance for any period during which, and to the extent that, such party or any
                                subcontractor is prevented from performing any obligation or service, in whole or in part, as a
                                result of causes beyond its reasonable control, and without its fault or negligence, including
                                without limitation, acts of God, strikes, lockouts, riots, acts of terrorism or war, epidemics,
                                communication line failures, power failures and government-imposed lockdowns or similar
                                restrictions.</p>
                            <p class="left_text"><span class="left2">xi.</span> <b>Updates to this User Agreement: </b>We may add to or change or update this User Agreement at
                                any time, from time to time, entirely at our own discretion, with or without any prior written
                                notice. You are responsible for checking this User Agreement periodically. Your use of the
                                Platform after any amendments to this User Agreement shall constitute your acceptance to
                                such amendments.</p>
                            <h2><span>22.</span>Grievance Officer/Designated Representative</h2>
                            <p class="left_text">In the event you have any grievance regarding anything related to this <b>User Agreement or Disclaimer
                                    or Cancellation & Refund Policy or Community Guidelines or Privacy Policy, </b>or with any content
                                or service of Ivacay, in that case you may freely write your concerns to the Grievance
                                Officer/Designated Officer appointed below:</p>
                            <p class="left_text2">● <strong>Name:</strong> Francis Banda</p>
                            <p class="left_text2">● <strong>Email:</strong> <a href="mailto:combinedsun@icloud.com">combinedsun@icloud.com</a></p>
                            <p class="left_text2">● <strong>Phone:</strong> 9499935368</p>
                            <p class="left_text2">● <strong>Postal:</strong> Po Box 81027, Rancho Santa Margarita, California – 92688</p>

                            <h2><span>23.</span>Feedback and Information</h2>
                            <p class="left_text">We welcome your questions or comments regarding this User Agreement. You can write to us via
                                email: <a href="mailto:combinedsun@icloud.com">combinedsun@icloud.com.</a>
                            </p>
                            <p style="margin: 100px 0px 0px 0px;">Last updated on <b>July 26, 2022</b></p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {{--    <div class="container about_con">--}}

    {{--    </div>--}}
@endsection